### ISSUE TITLE
Cannot select features on AGSFeatureTableLayer

### ISSUE THREAD

**Issue by ozcan-durak** [Esri/arcgis-runtime-samples-ios#184]
Hi,

When "AGSFeatureTableLayer" .setSelected enabled , Doesn't highlight the selected features.
Even when checked for isFeatureSelected turns to false. Somehow, Tried with **Offline Feature Editing sample**

Seems like a bug.

**Comment by goldenlimit** [comment]
For the question about how to use this method "isFeatureSelected" for AGSFeatureTableLayer, here are several things you need to take a look in order to make it work.
 
1. This selectioncolor property is only available in AGSFeatureTableLayer and AGSGraphicsLayer, therefore, you want to make sure the feature that you click is coming from either AGSFeatureTableLayer or AGSGraphicsLayer.
 
2. If you want to make it works in offline mode, then you should use AGSFeatureTableLayer; If you want to use in online mode you should use AGSGraphicsLayer, or follow this sample code from Runtime Quartz Feature layer selection, however, this sample is using another method called "selectFeaturesWithQuery:selectionMethod" from AGSFeatureLayer. Rather than the one you see from our  developer page for setSelected method Edit features—ArcGIS Runtime SDK for iOS | ArcGIS for Developers
 
3. Here I assume you want to use the AGSFeatureTableLayer to highlight the clicked features, here are some codes to show you how to make it work.
    
```
//instantiate variables in order to convert AGSfeatureLayer to AGSGDBFeatureServiceTable, and then use AGSGDBFeatureServiceTable to AGSFeatureTableLayer  
var featureServiceTable: AGSGDBFeatureServiceTable!  
var ftLayer: AGSFeatureTableLayer!  
  
//init AGSGDBFeatureServiceTable based  
let url = NSURL(string: "http://sampleserver6.arcgisonline.com/arcgis/rest/services/Wildfire/MapServer/0")  
  
//init AGSGDBFeatureServiceTable based on ArcGIS Featureservice/Mapservice URL  
featureServiceTable = AGSGDBFeatureServiceTable.init(serviceURL: url, credential: nil, spatialReference: AGSSpatialReference.wgs84SpatialReference())  
  
  
//create an local FeatureTableLayer based on featureServiceTable  
ftLayer = AGSFeatureTableLayer.init(featureTable: featureServiceTable)  
  
//define the selectionColor  
ftLayer.selectionColor = UIColor.redColor();  
  
  
//add the AGSFeatureTableLayer to map  
self.mapView.addMapLayer(ftLayer, withName: "FeatureLayer");  
  
  
//#pragma mark - AGSMapViewTouchDelegate methods  
//Use AGSMapViewTouchDelegate to trigger the click event  
func mapView(mapView: AGSMapView!, didClickAtPoint screen: CGPoint, mapPoint mappoint: AGSPoint!, features: [NSObject : AnyObject]!) {  
      
    ftLayer.clearSelection()  
      
    if features != nil {  
        //Need to define feature comes from which layer, by using featureservice's layer name  
        let array = features["Wildfire Response Points"] as! [AGSFeature]  
  
        for feature in array {  
            ftLayer.setSelected(true, forFeature: feature)  
            print("Is the feature selected?, Answer: \(ftLayer.isFeatureSelected(feature))")  
        }  
          
    } else {  
        print("No feature selected around your click.")  
          
    }  
}  
 
```
Hope this helps!

**Comment by goldenlimit** [comment]
In case you still not make it works. Here I shared with you a github sample that I created for this particular issue:
[AGSFeatureTableLayer Selection with Color](https://github.com/goldenlimit/developer-support/tree/Esri/gh-pages/runtime-ios/AGSFeatureTablelayer-Selectcolor-Swift)

**Comment by dg0yal** [comment]
For 100.x version of this capability, please refer to the Feature Layer Selection sample - https://github.com/Esri/arcgis-runtime-samples-ios/tree/master/arcgis-ios-sdk-samples/Features/Feature%20layer%20selection
